"""empty message

Revision ID: 109bbb4ea554
Revises: None
Create Date: 2015-07-01 06:26:44.640450

"""

# revision identifiers, used by Alembic.
revision = '109bbb4ea554'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
